import { SyntaxType } from 'structs';

const cachedSyntax = {
  content: { elementType: 'sentence' },
  children: [
    {
      content: { elementType: 'wg', role: 'cl' },
      children: [
        {
          content: { elementType: 'wg', class: 'cl', n: '450050030030230' },
          children: [
            {
              content: {
                elementType: 'w',
                class: 'conj',
                osisId: 'Rom.5.3!3',
                n: '450050030030010',
                lemma: 'δέ',
                strong: '1161',
                discontinuous: 'true',
                gloss: 'now',
                text: 'δέ',
                alignedWordIds: ['nvi_0'],
              },
              children: [],
            },
            { content: { elementType: 'pc', text: ',' }, children: [] },
            {
              content: { elementType: 'wg', class: 'cl', n: '450050030010220' },
              children: [
                {
                  content: {
                    elementType: 'w',
                    class: 'adv',
                    osisId: 'Rom.5.3!1',
                    n: '450050030010010',
                    lemma: 'οὐ',
                    strong: '3756',
                    gloss: 'Not',
                    text: 'οὐ',
                    alignedWordIds: ['nvi_1'],
                  },
                  children: [],
                },
                {
                  content: {
                    elementType: 'wg',
                    class: 'cl',
                    n: '450050030020013',
                  },
                  children: [
                    {
                      content: {
                        elementType: 'w',
                        role: 'advasdf',
                        class: 'adj',
                        osisId: 'Rom.5.3!2miker',
                        n: '450050030020010',
                        lemma: 'μόνος',
                        strong: '3440',
                        number: 'singular',
                        gender: 'neuter',
                        case: 'accusative',
                        gloss: 'only [so]',
                        text: 'μόνον',
                        alignedWordIds: ['nvi_2'],
                      },
                      children: [],
                    },
                  ],
                },
                {
                  content: {
                    elementType: 'w',
                    class: 'conj',
                    osisId: 'Rom.5.3!4',
                    n: '450050030040010',
                    lemma: 'ἀλλά',
                    strong: '235',
                    gloss: 'but',
                    text: 'ἀλλὰ',
                    alignedWordIds: ['nvi_5'],
                  },
                  children: [],
                },
                {
                  content: {
                    elementType: 'wg',
                    class: 'cl',
                    n: '450050030050190',
                    head: 'true',
                  },
                  children: [
                    {
                      content: {
                        elementType: 'w',
                        role: 'adv',
                        class: 'adv',
                        osisId: 'Rom.5.3!5',
                        n: '450050030050010',
                        lemma: 'καί',
                        strong: '2532',
                        gloss: 'also',
                        text: 'καὶ',
                        alignedWordIds: ['nvi_6'],
                      },
                      children: [],
                    },
                    {
                      content: {
                        elementType: 'w',
                        role: 'v',
                        class: 'verb',
                        osisId: 'Rom.5.3!6',
                        n: '450050030060010',
                        lemma: 'καυχάομαι',
                        strong: '2744',
                        number: 'plural',
                        person: 'first',
                        tense: 'present',
                        voice: 'middlepassive',
                        mood: 'indicative',
                        head: 'true',
                        gloss: 'we glory',
                        text: 'καυχώμεθα',
                        alignedWordIds: [],
                      },
                      children: [],
                    },
                    {
                      content: {
                        elementType: 'wg',
                        role: 'adv',
                        class: 'pp',
                        n: '450050030070030',
                        articular: 'true',
                      },
                      children: [
                        {
                          content: {
                            elementType: 'w',
                            class: 'prep',
                            osisId: 'Rom.5.3!7',
                            n: '450050030070010',
                            lemma: 'ἐν',
                            strong: '1722',
                            gloss: 'in',
                            text: 'ἐν',
                            alignedWordIds: ['nvi_7'],
                          },
                          children: [],
                        },
                        {
                          content: {
                            elementType: 'wg',
                            class: 'np',
                            n: '450050030080020',
                            articular: 'true',
                            head: 'true',
                          },
                          children: [
                            {
                              content: {
                                elementType: 'w',
                                class: 'det',
                                osisId: 'Rom.5.3!8',
                                n: '450050030080010',
                                lemma: 'ὁ',
                                strong: '3588',
                                number: 'plural',
                                gender: 'feminine',
                                case: 'dative',
                                gloss: '-',
                                text: 'ταῖς',
                                alignedWordIds: ['nvi_8', 'nvi_9'],
                              },
                              children: [],
                            },
                            {
                              content: {
                                elementType: 'w',
                                class: 'noun',
                                type: 'common',
                                osisId: 'Rom.5.3!9',
                                n: '450050030090010',
                                lemma: 'θλῖψις',
                                strong: '2347',
                                number: 'plural',
                                gender: 'feminine',
                                case: 'dative',
                                head: 'true',
                                gloss: 'tribulations',
                                text: 'θλίψεσιν',
                                alignedWordIds: ['nvi_8', 'nvi_9'],
                              },
                              children: [],
                            },
                            {
                              content: { elementType: 'pc', text: ',' },
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      content: {
                        elementType: 'wg',
                        role: 'adv',
                        class: 'cl',
                        n: '450050030100140',
                      },
                      children: [
                        {
                          content: {
                            elementType: 'wg',
                            class: 'cl',
                            n: '450050030100013',
                            head: 'true',
                          },
                          children: [
                            {
                              content: {
                                elementType: 'w',
                                role: 'v',
                                class: 'verb',
                                osisId: 'Rom.5.3!10',
                                n: '450050030100010',
                                lemma: 'οἶδα',
                                strong: '1492',
                                number: 'plural',
                                gender: 'masculine',
                                case: 'nominative',
                                tense: 'perfect',
                                voice: 'active',
                                mood: 'participle',
                                type: '?',
                                head: 'true',
                                gloss: 'knowing',
                                text: 'εἰδότες',
                                alignedWordIds: ['nvi_11'],
                              },
                              children: [],
                            },
                          ],
                        },
                        {
                          content: {
                            elementType: 'wg',
                            class: 'cl',
                            n: '450050030110130',
                          },
                          children: [
                            {
                              content: {
                                elementType: 'w',
                                class: 'conj',
                                osisId: 'Rom.5.3!11',
                                n: '450050030110010',
                                lemma: 'ὅτι',
                                strong: '3754',
                                gloss: 'that',
                                text: 'ὅτι',
                                alignedWordIds: ['nvi_12'],
                              },
                              children: [],
                            },
                            {
                              content: {
                                elementType: 'wg',
                                class: 'cl',
                                n: '450050030120120',
                              },
                              children: [
                                {
                                  content: {
                                    elementType: 'wg',
                                    class: 'cl',
                                    n: '450050030120040',
                                    head: 'true',
                                  },
                                  children: [
                                    {
                                      content: {
                                        elementType: 'wg',
                                        role: 's',
                                        class: 'np',
                                        n: '450050030120020',
                                        articular: 'true',
                                      },
                                      children: [
                                        {
                                          content: {
                                            elementType: 'w',
                                            class: 'det',
                                            osisId: 'Rom.5.3!12',
                                            n: '450050030120010',
                                            lemma: 'ὁ',
                                            strong: '3588',
                                            number: 'singular',
                                            gender: 'feminine',
                                            case: 'nominative',
                                            gloss: '-',
                                            text: 'ἡ',
                                            alignedWordIds: ['nvi_13'],
                                          },
                                          children: [],
                                        },
                                        {
                                          content: {
                                            elementType: 'w',
                                            class: 'noun',
                                            type: 'common',
                                            osisId: 'Rom.5.3!13',
                                            n: '450050030130010',
                                            lemma: 'θλῖψις',
                                            strong: '2347',
                                            number: 'singular',
                                            gender: 'feminine',
                                            case: 'nominative',
                                            head: 'true',
                                            gloss: 'tribulation',
                                            text: 'θλῖψις',
                                            alignedWordIds: ['nvi_14'],
                                          },
                                          children: [],
                                        },
                                      ],
                                    },
                                    {
                                      content: {
                                        elementType: 'w',
                                        role: 'o',
                                        class: 'noun',
                                        type: 'common',
                                        osisId: 'Rom.5.3!14',
                                        n: '450050030140010',
                                        lemma: 'ὑπομονή',
                                        strong: '5281',
                                        number: 'singular',
                                        gender: 'feminine',
                                        case: 'accusative',
                                        gloss: 'perseverance',
                                        text: 'ὑπομονὴν',
                                        alignedWordIds: ['nvi_16'],
                                      },
                                      children: [],
                                    },
                                    {
                                      content: {
                                        elementType: 'w',
                                        role: 'v',
                                        class: 'verb',
                                        osisId: 'Rom.5.3!15',
                                        n: '450050030150010',
                                        lemma: 'κατεργάζομαι',
                                        strong: '2716',
                                        number: 'singular',
                                        person: 'third',
                                        tense: 'present',
                                        voice: 'middlepassive',
                                        mood: 'indicative',
                                        head: 'true',
                                        gloss: 'produces',
                                        text: 'κατεργάζεται',
                                        alignedWordIds: ['nvi_15'],
                                      },
                                      children: [],
                                    },
                                    {
                                      content: { elementType: 'pc', text: ',' },
                                      children: [],
                                    },
                                  ],
                                },
                                {
                                  content: {
                                    elementType: 'w',
                                    class: 'conj',
                                    osisId: 'Rom.5.4!2',
                                    n: '450050040020010',
                                    lemma: 'δέ',
                                    strong: '1161',
                                    discontinuous: 'true',
                                    gloss: 'And',
                                    text: 'δὲ',
                                    alignedWordIds: [],
                                  },
                                  children: [],
                                },
                                {
                                  content: {
                                    elementType: 'wg',
                                    class: 'cl',
                                    n: '450050040010030',
                                    articular: 'true',
                                  },
                                  children: [
                                    {
                                      content: {
                                        elementType: 'wg',
                                        role: 's',
                                        class: 'np',
                                        n: '450050040010020',
                                        articular: 'true',
                                        head: 'true',
                                      },
                                      children: [
                                        {
                                          content: {
                                            elementType: 'w',
                                            class: 'det',
                                            osisId: 'Rom.5.4!1',
                                            n: '450050040010010',
                                            lemma: 'ὁ',
                                            strong: '3588',
                                            number: 'singular',
                                            gender: 'feminine',
                                            case: 'nominative',
                                            gloss: '-',
                                            text: 'ἡ',
                                            alignedWordIds: [],
                                          },
                                          children: [],
                                        },
                                        {
                                          content: {
                                            elementType: 'w',
                                            class: 'noun',
                                            type: 'common',
                                            osisId: 'Rom.5.4!3',
                                            n: '450050040030010',
                                            lemma: 'ὑπομονή',
                                            strong: '5281',
                                            number: 'singular',
                                            gender: 'feminine',
                                            case: 'nominative',
                                            head: 'true',
                                            gloss: 'perseverance',
                                            text: 'ὑπομονὴ',
                                            alignedWordIds: [],
                                          },
                                          children: [],
                                        },
                                      ],
                                    },
                                    {
                                      content: {
                                        elementType: 'w',
                                        role: 'o',
                                        class: 'noun',
                                        type: 'common',
                                        osisId: 'Rom.5.4!4',
                                        n: '450050040040010',
                                        lemma: 'δοκιμή',
                                        strong: '1382',
                                        number: 'singular',
                                        gender: 'feminine',
                                        case: 'accusative',
                                        gloss: 'character',
                                        text: 'δοκιμήν',
                                        alignedWordIds: [],
                                      },
                                      children: [],
                                    },
                                    {
                                      content: { elementType: 'pc', text: ',' },
                                      children: [],
                                    },
                                  ],
                                },
                                {
                                  content: {
                                    elementType: 'w',
                                    class: 'conj',
                                    osisId: 'Rom.5.4!6',
                                    n: '450050040060010',
                                    lemma: 'δέ',
                                    strong: '1161',
                                    discontinuous: 'true',
                                    gloss: 'and',
                                    text: 'δὲ',
                                    alignedWordIds: [],
                                  },
                                  children: [],
                                },
                                {
                                  content: {
                                    elementType: 'wg',
                                    class: 'cl',
                                    n: '450050040050030',
                                    articular: 'true',
                                  },
                                  children: [
                                    {
                                      content: {
                                        elementType: 'wg',
                                        role: 's',
                                        class: 'np',
                                        n: '450050040050020',
                                        articular: 'true',
                                        head: 'true',
                                      },
                                      children: [
                                        {
                                          content: {
                                            elementType: 'w',
                                            class: 'det',
                                            osisId: 'Rom.5.4!5',
                                            n: '450050040050010',
                                            lemma: 'ὁ',
                                            strong: '3588',
                                            number: 'singular',
                                            gender: 'feminine',
                                            case: 'nominative',
                                            gloss: '-',
                                            text: 'ἡ',
                                            alignedWordIds: [],
                                          },
                                          children: [],
                                        },
                                        {
                                          content: {
                                            elementType: 'w',
                                            class: 'noun',
                                            type: 'common',
                                            osisId: 'Rom.5.4!7',
                                            n: '450050040070010',
                                            lemma: 'δοκιμή',
                                            strong: '1382',
                                            number: 'singular',
                                            gender: 'feminine',
                                            case: 'nominative',
                                            head: 'true',
                                            gloss: 'character',
                                            text: 'δοκιμὴ',
                                            alignedWordIds: [],
                                          },
                                          children: [],
                                        },
                                      ],
                                    },
                                    {
                                      content: {
                                        elementType: 'w',
                                        role: 'o',
                                        class: 'noun',
                                        type: 'common',
                                        osisId: 'Rom.5.4!8',
                                        n: '450050040080010',
                                        lemma: 'ἐλπίς',
                                        strong: '1680',
                                        number: 'singular',
                                        gender: 'feminine',
                                        case: 'accusative',
                                        gloss: 'hope',
                                        text: 'ἐλπίδα',
                                        alignedWordIds: [],
                                      },
                                      children: [],
                                    },
                                    {
                                      content: { elementType: 'pc', text: '·' },
                                      children: [],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  _syntaxType: SyntaxType.Mapped,
};

export default cachedSyntax;
