const books = [
  {
    BookNumber: 1,
    ParaText: 'GEN',
    OSIS: 'Gen',
    ClearBible: 'gn',
    SBLGNT: '',
    EnglishBookName: 'Genesis',
    ChapterCount: 50,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 2,
    ParaText: 'EXO',
    OSIS: 'Exod',
    ClearBible: 'ex',
    SBLGNT: '',
    EnglishBookName: 'Exodus',
    ChapterCount: 40,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 3,
    ParaText: 'LEV',
    OSIS: 'Lev',
    ClearBible: 'lv',
    SBLGNT: '',
    EnglishBookName: 'Leviticus',
    ChapterCount: 27,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 4,
    ParaText: 'NUM',
    OSIS: 'Num',
    ClearBible: 'nu',
    SBLGNT: '',
    EnglishBookName: 'Numbers',
    ChapterCount: 36,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 5,
    ParaText: 'DEU',
    OSIS: 'Deut',
    ClearBible: 'dt',
    SBLGNT: '',
    EnglishBookName: 'Deuteronomy',
    ChapterCount: 34,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 6,
    ParaText: 'JOS',
    OSIS: 'Josh',
    ClearBible: 'js',
    SBLGNT: '',
    EnglishBookName: 'Joshua',
    ChapterCount: 24,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 7,
    ParaText: 'JDG',
    OSIS: 'Judg',
    ClearBible: 'ju',
    SBLGNT: '',
    EnglishBookName: 'Judges',
    ChapterCount: 21,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 8,
    ParaText: 'RUT',
    OSIS: 'Ruth',
    ClearBible: 'ru',
    SBLGNT: '',
    EnglishBookName: 'Ruth',
    ChapterCount: 4,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 9,
    ParaText: '1SA',
    OSIS: '1Sam',
    ClearBible: '1s',
    SBLGNT: '',
    EnglishBookName: '1 Samuel',
    ChapterCount: 31,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 10,
    ParaText: '2SA',
    OSIS: '2Sam',
    ClearBible: '2s',
    SBLGNT: '',
    EnglishBookName: '2 Samuel',
    ChapterCount: 24,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 11,
    ParaText: '1KI',
    OSIS: '1Kgs',
    ClearBible: '1k',
    SBLGNT: '',
    EnglishBookName: '1 Kings',
    ChapterCount: 22,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 12,
    ParaText: '2KI',
    OSIS: '2Kgs',
    ClearBible: '2k',
    SBLGNT: '',
    EnglishBookName: '2 Kings',
    ChapterCount: 25,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 13,
    ParaText: '1CH',
    OSIS: '1Chr',
    ClearBible: '1c',
    SBLGNT: '',
    EnglishBookName: '1 Chronicles',
    ChapterCount: 29,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 14,
    ParaText: '2CH',
    OSIS: '2Chr',
    ClearBible: '2c',
    SBLGNT: '',
    EnglishBookName: '2 Chronicles',
    ChapterCount: 36,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 15,
    ParaText: 'EZR',
    OSIS: 'Ezra',
    ClearBible: 'er',
    SBLGNT: '',
    EnglishBookName: 'Ezra',
    ChapterCount: 10,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 16,
    ParaText: 'NEH',
    OSIS: 'Neh',
    ClearBible: 'ne',
    SBLGNT: '',
    EnglishBookName: 'Nehemiah',
    ChapterCount: 13,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 17,
    ParaText: 'EST',
    OSIS: 'Esth',
    ClearBible: 'es',
    SBLGNT: '',
    EnglishBookName: 'Esther (Hebrew)',
    ChapterCount: 10,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 18,
    ParaText: 'JOB',
    OSIS: 'Job',
    ClearBible: 'jb',
    SBLGNT: '',
    EnglishBookName: 'Job',
    ChapterCount: 42,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 19,
    ParaText: 'PSA',
    OSIS: 'Ps',
    ClearBible: 'ps',
    SBLGNT: '',
    EnglishBookName: 'Psalms',
    ChapterCount: 150,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 20,
    ParaText: 'PRO',
    OSIS: 'Prov',
    ClearBible: 'pr',
    SBLGNT: '',
    EnglishBookName: 'Proverbs',
    ChapterCount: 31,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 21,
    ParaText: 'ECC',
    OSIS: 'Eccl',
    ClearBible: 'ec',
    SBLGNT: '',
    EnglishBookName: 'Ecclesiastes',
    ChapterCount: 12,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 22,
    ParaText: 'SNG',
    OSIS: 'Song',
    ClearBible: 'ca',
    SBLGNT: '',
    EnglishBookName: 'Song of Songs',
    ChapterCount: 8,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 23,
    ParaText: 'ISA',
    OSIS: 'Isa',
    ClearBible: 'is',
    SBLGNT: '',
    EnglishBookName: 'Isaiah',
    ChapterCount: 66,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 24,
    ParaText: 'JER',
    OSIS: 'Jer',
    ClearBible: 'je',
    SBLGNT: '',
    EnglishBookName: 'Jeremiah',
    ChapterCount: 52,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 25,
    ParaText: 'LAM',
    OSIS: 'Lam',
    ClearBible: 'lm',
    SBLGNT: '',
    EnglishBookName: 'Lamentations',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 26,
    ParaText: 'EZK',
    OSIS: 'Ezek',
    ClearBible: 'ek',
    SBLGNT: '',
    EnglishBookName: 'Ezekiel',
    ChapterCount: 48,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 27,
    ParaText: 'DAN',
    OSIS: 'Dan',
    ClearBible: 'da',
    SBLGNT: '',
    EnglishBookName: 'Daniel (Hebrew)',
    ChapterCount: 12,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 28,
    ParaText: 'HOS',
    OSIS: 'Hos',
    ClearBible: 'ho',
    SBLGNT: '',
    EnglishBookName: 'Hosea',
    ChapterCount: 14,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 29,
    ParaText: 'JOL',
    OSIS: 'Joel',
    ClearBible: 'jl',
    SBLGNT: '',
    EnglishBookName: 'Joel',
    ChapterCount: 4,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 30,
    ParaText: 'AMO',
    OSIS: 'Amos',
    ClearBible: 'am',
    SBLGNT: '',
    EnglishBookName: 'Amos',
    ChapterCount: 9,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 31,
    ParaText: 'OBA',
    OSIS: 'Obad',
    ClearBible: 'ob',
    SBLGNT: '',
    EnglishBookName: 'Obadiah',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 32,
    ParaText: 'JON',
    OSIS: 'Jonah',
    ClearBible: 'jn',
    SBLGNT: '',
    EnglishBookName: 'Jonah',
    ChapterCount: 4,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 33,
    ParaText: 'MIC',
    OSIS: 'Mic',
    ClearBible: 'mi',
    SBLGNT: '',
    EnglishBookName: 'Micah',
    ChapterCount: 7,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 34,
    ParaText: 'NAM',
    OSIS: 'Nah',
    ClearBible: 'na',
    SBLGNT: '',
    EnglishBookName: 'Nahum',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 35,
    ParaText: 'HAB',
    OSIS: 'Hab',
    ClearBible: 'hb',
    SBLGNT: '',
    EnglishBookName: 'Habakkuk',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 36,
    ParaText: 'ZEP',
    OSIS: 'Zeph',
    ClearBible: 'zp',
    SBLGNT: '',
    EnglishBookName: 'Zephaniah',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 37,
    ParaText: 'HAG',
    OSIS: 'Hag',
    ClearBible: 'hg',
    SBLGNT: '',
    EnglishBookName: 'Haggai',
    ChapterCount: 2,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 38,
    ParaText: 'ZEC',
    OSIS: 'Zech',
    ClearBible: 'zc',
    SBLGNT: '',
    EnglishBookName: 'Zechariah',
    ChapterCount: 14,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 39,
    ParaText: 'MAL',
    OSIS: 'Mal',
    ClearBible: 'ma',
    SBLGNT: '',
    EnglishBookName: 'Malachi',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 40,
    ParaText: 'MAT',
    OSIS: 'Matt',
    ClearBible: 'Mat',
    SBLGNT: 'Mt',
    EnglishBookName: 'Matthew',
    ChapterCount: 28,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 41,
    ParaText: 'MRK',
    OSIS: 'Mark',
    ClearBible: 'Mrk',
    SBLGNT: 'Mk',
    EnglishBookName: 'Mark',
    ChapterCount: 16,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 42,
    ParaText: 'LUK',
    OSIS: 'Luke',
    ClearBible: 'Luk',
    SBLGNT: 'Lk',
    EnglishBookName: 'Luke',
    ChapterCount: 24,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 43,
    ParaText: 'JHN',
    OSIS: 'John',
    ClearBible: 'Jhn',
    SBLGNT: 'Jn',
    EnglishBookName: 'John',
    ChapterCount: 21,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 44,
    ParaText: 'ACT',
    OSIS: 'Acts',
    ClearBible: 'Act',
    SBLGNT: 'Ac',
    EnglishBookName: 'Acts',
    ChapterCount: 28,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 45,
    ParaText: 'ROM',
    OSIS: 'Rom',
    ClearBible: 'Rom',
    SBLGNT: 'Ro',
    EnglishBookName: 'Romans',
    ChapterCount: 16,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 46,
    ParaText: '1CO',
    OSIS: '1Cor',
    ClearBible: '1Co',
    SBLGNT: '1Co',
    EnglishBookName: '1 Corinthians',
    ChapterCount: 16,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 47,
    ParaText: '2CO',
    OSIS: '2Cor',
    ClearBible: '2Co',
    SBLGNT: '2Co',
    EnglishBookName: '2 Corinthians',
    ChapterCount: 13,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 48,
    ParaText: 'GAL',
    OSIS: 'Gal',
    ClearBible: 'Gal',
    SBLGNT: 'Ga',
    EnglishBookName: 'Galatians',
    ChapterCount: 6,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 49,
    ParaText: 'EPH',
    OSIS: 'Eph',
    ClearBible: 'Eph',
    SBLGNT: 'Eph',
    EnglishBookName: 'Ephesians',
    ChapterCount: 6,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 50,
    ParaText: 'PHP',
    OSIS: 'Phil',
    ClearBible: 'Php',
    SBLGNT: 'Php',
    EnglishBookName: 'Philippians',
    ChapterCount: 4,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 51,
    ParaText: 'COL',
    OSIS: 'Col',
    ClearBible: 'Col',
    SBLGNT: 'Col',
    EnglishBookName: 'Colossians',
    ChapterCount: 4,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 52,
    ParaText: '1TH',
    OSIS: '1Thess',
    ClearBible: '1Th',
    SBLGNT: '1Th',
    EnglishBookName: '1 Thessalonians',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 53,
    ParaText: '2TH',
    OSIS: '2Thess',
    ClearBible: '2Th',
    SBLGNT: '2Th',
    EnglishBookName: '2 Thessalonians',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 54,
    ParaText: '1TI',
    OSIS: '1Tim',
    ClearBible: '1Tm',
    SBLGNT: '1Ti',
    EnglishBookName: '1 Timothy',
    ChapterCount: 6,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 55,
    ParaText: '2TI',
    OSIS: '2Tim',
    ClearBible: '2Tm',
    SBLGNT: '2Ti',
    EnglishBookName: '2 Timothy',
    ChapterCount: 4,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 56,
    ParaText: 'TIT',
    OSIS: 'Titus',
    ClearBible: 'Tit',
    SBLGNT: 'Tit',
    EnglishBookName: 'Titus',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 57,
    ParaText: 'PHM',
    OSIS: 'Phlm',
    ClearBible: 'Phm',
    SBLGNT: 'Phm',
    EnglishBookName: 'Philemon',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 58,
    ParaText: 'HEB',
    OSIS: 'Heb',
    ClearBible: 'Heb',
    SBLGNT: 'Heb',
    EnglishBookName: 'Hebrews',
    ChapterCount: 13,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 59,
    ParaText: 'JAS',
    OSIS: 'Jas',
    ClearBible: 'Jms',
    SBLGNT: 'Jas',
    EnglishBookName: 'James',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 60,
    ParaText: '1PE',
    OSIS: '1Pet',
    ClearBible: '1Pe',
    SBLGNT: '1Pe',
    EnglishBookName: '1 Peter',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 61,
    ParaText: '2PE',
    OSIS: '2Pet',
    ClearBible: '2Pe',
    SBLGNT: '2Pe',
    EnglishBookName: '2 Peter',
    ChapterCount: 3,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 62,
    ParaText: '1JN',
    OSIS: '1John',
    ClearBible: '1Jn',
    SBLGNT: '1Jn',
    EnglishBookName: '1 John',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 63,
    ParaText: '2JN',
    OSIS: '2John',
    ClearBible: '2Jn',
    SBLGNT: '2Jn',
    EnglishBookName: '2 John',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 64,
    ParaText: '3JN',
    OSIS: '3John',
    ClearBible: '3Jn',
    SBLGNT: '3Jn',
    EnglishBookName: '3 John',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 65,
    ParaText: 'JUD',
    OSIS: 'Jude',
    ClearBible: 'Jud',
    SBLGNT: 'Jud',
    EnglishBookName: 'Jude',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 66,
    ParaText: 'REV',
    OSIS: 'Rev',
    ClearBible: 'Rev',
    SBLGNT: 'Re',
    EnglishBookName: 'Revelation',
    ChapterCount: 22,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 67,
    ParaText: 'TOB',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Tobit',
    ChapterCount: 14,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 68,
    ParaText: 'JDT',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Judith',
    ChapterCount: 16,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 69,
    ParaText: 'ESG',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Esther Greek',
    ChapterCount: 10,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 70,
    ParaText: 'WIS',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Wisdom of Solomon',
    ChapterCount: 19,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 71,
    ParaText: 'SIR',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Sirach (Ecclesiasticus)',
    ChapterCount: 51,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 72,
    ParaText: 'BAR',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Baruch',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 73,
    ParaText: 'LJE',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Letter of Jeremiah',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 74,
    ParaText: 'S3Y',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Song of 3 Young Men',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 75,
    ParaText: 'SUS',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Susanna',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 76,
    ParaText: 'BEL',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Bel and the Dragon',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 77,
    ParaText: '1MA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '1 Maccabees',
    ChapterCount: 16,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 78,
    ParaText: '2MA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '2 Maccabees',
    ChapterCount: 15,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 79,
    ParaText: '3MA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '3 Maccabees',
    ChapterCount: 7,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 80,
    ParaText: '4MA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '4 Maccabees',
    ChapterCount: 18,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 81,
    ParaText: '1ES',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '1 Esdras (Greek)',
    ChapterCount: 9,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 82,
    ParaText: '2ES',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '2 Esdras (Latin)',
    ChapterCount: 16,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 83,
    ParaText: 'MAN',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Prayer of Manasseh',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 84,
    ParaText: 'PS2',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Psalm 151',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 85,
    ParaText: 'ODA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Odes',
    ChapterCount: 14,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 86,
    ParaText: 'PSS',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Psalms of Solomon',
    ChapterCount: 18,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 87,
    ParaText: 'JSA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Joshua A. *obsolete*',
    ChapterCount: 24,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 88,
    ParaText: 'JDB',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Judges B. *obsolete*',
    ChapterCount: 21,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 89,
    ParaText: 'TBS',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Tobit S. *obsolete*',
    ChapterCount: 14,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 90,
    ParaText: 'SST',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Susanna Th. *obsolete*',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 91,
    ParaText: 'DNT',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Daniel Th. *obsolete*',
    ChapterCount: 12,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 92,
    ParaText: 'BLT',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Bel Th. *obsolete*',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 93,
    ParaText: 'XXA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra A',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 94,
    ParaText: 'XXB',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra B',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 95,
    ParaText: 'XXC',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra C',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 96,
    ParaText: 'XXD',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra D',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 97,
    ParaText: 'XXE',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra E',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 98,
    ParaText: 'XXF',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra F',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 99,
    ParaText: 'XXG',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Extra G',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 100,
    ParaText: 'FRT',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Front Matter',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 101,
    ParaText: 'BAK',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Back Matter',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 102,
    ParaText: 'OTH',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Other Matter',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 103,
    ParaText: '3ES',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '3 Ezra *obsolete*',
    ChapterCount: '',
    IsBibleBook: 'True',
  },
  {
    BookNumber: 104,
    ParaText: 'EZA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Apocalypse of Ezra',
    ChapterCount: 12,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 105,
    ParaText: '5EZ',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '5 Ezra (Latin Prologue)',
    ChapterCount: '',
    IsBibleBook: 'True',
  },
  {
    BookNumber: 106,
    ParaText: '6EZ',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '6 Ezra (Latin Epilogue)',
    ChapterCount: 2,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 107,
    ParaText: 'INT',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Introduction',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 108,
    ParaText: 'CNC',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Concordance',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 109,
    ParaText: 'GLO',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Glossary',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 110,
    ParaText: 'TDX',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Topical Index',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 111,
    ParaText: 'NDX',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Names Index',
    ChapterCount: '',
    IsBibleBook: 'False',
  },
  {
    BookNumber: 112,
    ParaText: 'DAG',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Daniel Greek',
    ChapterCount: 12,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 113,
    ParaText: 'PS3',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Psalms 152-155',
    ChapterCount: '',
    IsBibleBook: 'True',
  },
  {
    BookNumber: 114,
    ParaText: '2BA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '2 Baruch (Apocalypse)',
    ChapterCount: '',
    IsBibleBook: 'True',
  },
  {
    BookNumber: 115,
    ParaText: 'LBA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Letter of Baruch',
    ChapterCount: '',
    IsBibleBook: 'True',
  },
  {
    BookNumber: 116,
    ParaText: 'JUB',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Jubilees',
    ChapterCount: 34,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 117,
    ParaText: 'ENO',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Enoch',
    ChapterCount: 42,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 118,
    ParaText: '1MQ',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '1 Meqabyan',
    ChapterCount: 36,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 119,
    ParaText: '2MQ',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '2 Meqabyan',
    ChapterCount: '',
    IsBibleBook: 'True',
  },
  {
    BookNumber: 120,
    ParaText: '3MQ',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '3 Meqabyan',
    ChapterCount: 10,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 121,
    ParaText: 'REP',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Reproof (Proverbs 25-31)',
    ChapterCount: 6,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 122,
    ParaText: '4BA',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: '4 Baruch (Rest of Baruch)',
    ChapterCount: 5,
    IsBibleBook: 'True',
  },
  {
    BookNumber: 123,
    ParaText: 'LAO',
    OSIS: '',
    ClearBible: '',
    SBLGNT: '',
    EnglishBookName: 'Laodiceans',
    ChapterCount: 1,
    IsBibleBook: 'True',
  },
];

export default books;
